name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build
        run: |
          # Copy GitHub Pages specific files
          cp index.github-pages.html index.html
          cp config.github-pages.js config.js
          
          # Update GitHub Pages URL in config
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          GITHUB_USERNAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)
          sed -i "s/\[your-username\]/$GITHUB_USERNAME/g" config.js
          sed -i "s/\[repository-name\]/$REPO_NAME/g" config.js
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 